-- 042 — Nettoyage RLS : suppression d'une politique morte sur public.users
--
-- Contexte : le Performance Advisor de Supabase (lint 0006
-- multiple_permissive_policies) signale les tables ayant plusieurs politiques
-- PERMISSIVE pour un même rôle+action (chacune évaluée à chaque requête).
-- La grande majorité de ces cas vient du modèle de sécurité VOULU
-- (admin_all + accès-par-site + demandeur), non réductible sans réécrire la
-- RLS. Un audit exhaustif (54 tables) n'a trouvé qu'UNE seule politique
-- réellement REDONDANTE — supprimable sans retirer aucun accès.
--
-- `users_manager_provision` (FOR ALL) est entièrement couverte par
-- `users_manager_all` (FOR ALL) depuis le durcissement v0.29 :
--   manager_provision USING : manager ∧ role∈{tech,lecteur,demandeur} ∧ shares_site_with(id)
--   manager_all       USING : manager ∧ ( self ∨ (role∉{admin,manager} ∧ shares_site_with(id)) )
--   manager_provision CHECK : manager ∧ role∈{tech,lecteur,demandeur}
--   manager_all       CHECK : manager ∧ ( role∉{admin,manager} ∨ self )
-- Comme {tech,lecteur,demandeur} = NOT {admin,manager}, on a
-- provision ⊆ all sur USING ET WITH CHECK, pour les 4 commandes du FOR ALL.
-- Les politiques étant PERMISSIVE (OR), retirer la sous-politique ne change
-- l'union d'aucun accès manager. Idempotent.

DROP POLICY IF EXISTS users_manager_provision ON public.users;
