/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DefinirMotDePasseRouteImport } from './routes/definir-mot-de-passe'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUtilisateursRouteImport } from './routes/_app/utilisateurs'
import { Route as AppTravauxRouteImport } from './routes/_app/travaux'
import { Route as AppSitesRouteImport } from './routes/_app/sites'
import { Route as AppRelevesRouteImport } from './routes/_app/releves'
import { Route as AppRegistreRouteImport } from './routes/_app/registre'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AppPrestatairesRouteImport } from './routes/_app/prestataires'
import { Route as AppPlanningRouteImport } from './routes/_app/planning'
import { Route as AppOrdresTravailRouteImport } from './routes/_app/ordres-travail'
import { Route as AppLocalisationsRouteImport } from './routes/_app/localisations'
import { Route as AppInvestissementsRouteImport } from './routes/_app/investissements'
import { Route as AppGammesRouteImport } from './routes/_app/gammes'
import { Route as AppEquipementsRouteImport } from './routes/_app/equipements'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDemandesRouteImport } from './routes/_app/demandes'
import { Route as AppBibliothequeRouteImport } from './routes/_app/bibliotheque'
import { Route as AppUtilisateursIndexRouteImport } from './routes/_app/utilisateurs/index'
import { Route as AppTravauxIndexRouteImport } from './routes/_app/travaux/index'
import { Route as AppPrestatairesIndexRouteImport } from './routes/_app/prestataires/index'
import { Route as AppInvestissementsIndexRouteImport } from './routes/_app/investissements/index'
import { Route as AppDemandesIndexRouteImport } from './routes/_app/demandes/index'
import { Route as AppBibliothequeIndexRouteImport } from './routes/_app/bibliotheque/index'
import { Route as AppUtilisateursUtilisateurRouteImport } from './routes/_app/utilisateurs/$utilisateur'
import { Route as AppTravauxTravauxRouteImport } from './routes/_app/travaux/$travaux'
import { Route as AppPrestatairesPrestataireRouteImport } from './routes/_app/prestataires/$prestataire'
import { Route as AppLocalisationsSplatRouteImport } from './routes/_app/localisations/$'
import { Route as AppInvestissementsInvestissementRouteImport } from './routes/_app/investissements/$investissement'
import { Route as AppGammesSplatRouteImport } from './routes/_app/gammes/$'
import { Route as AppEquipementsSplatRouteImport } from './routes/_app/equipements/$'
import { Route as AppDemandesDemandeRouteImport } from './routes/_app/demandes/$demande'
import { Route as AppBibliothequeSplatRouteImport } from './routes/_app/bibliotheque/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirMotDePasseRoute = DefinirMotDePasseRouteImport.update({
  id: '/definir-mot-de-passe',
  path: '/definir-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppTravauxRoute = AppTravauxRouteImport.update({
  id: '/travaux',
  path: '/travaux',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppRelevesRoute = AppRelevesRouteImport.update({
  id: '/releves',
  path: '/releves',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistreRoute = AppRegistreRouteImport.update({
  id: '/registre',
  path: '/registre',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppPrestatairesRoute = AppPrestatairesRouteImport.update({
  id: '/prestataires',
  path: '/prestataires',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdresTravailRoute = AppOrdresTravailRouteImport.update({
  id: '/ordres-travail',
  path: '/ordres-travail',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalisationsRoute = AppLocalisationsRouteImport.update({
  id: '/localisations',
  path: '/localisations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestissementsRoute = AppInvestissementsRouteImport.update({
  id: '/investissements',
  path: '/investissements',
  getParentRoute: () => AppRoute,
} as any)
const AppGammesRoute = AppGammesRouteImport.update({
  id: '/gammes',
  path: '/gammes',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipementsRoute = AppEquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandesRoute = AppDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliothequeRoute = AppBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilisateursIndexRoute = AppUtilisateursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUtilisateursRoute,
} as any)
const AppTravauxIndexRoute = AppTravauxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTravauxRoute,
} as any)
const AppPrestatairesIndexRoute = AppPrestatairesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPrestatairesRoute,
} as any)
const AppInvestissementsIndexRoute = AppInvestissementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvestissementsRoute,
} as any)
const AppDemandesIndexRoute = AppDemandesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDemandesRoute,
} as any)
const AppBibliothequeIndexRoute = AppBibliothequeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBibliothequeRoute,
} as any)
const AppUtilisateursUtilisateurRoute =
  AppUtilisateursUtilisateurRouteImport.update({
    id: '/$utilisateur',
    path: '/$utilisateur',
    getParentRoute: () => AppUtilisateursRoute,
  } as any)
const AppTravauxTravauxRoute = AppTravauxTravauxRouteImport.update({
  id: '/$travaux',
  path: '/$travaux',
  getParentRoute: () => AppTravauxRoute,
} as any)
const AppPrestatairesPrestataireRoute =
  AppPrestatairesPrestataireRouteImport.update({
    id: '/$prestataire',
    path: '/$prestataire',
    getParentRoute: () => AppPrestatairesRoute,
  } as any)
const AppLocalisationsSplatRoute = AppLocalisationsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppLocalisationsRoute,
} as any)
const AppInvestissementsInvestissementRoute =
  AppInvestissementsInvestissementRouteImport.update({
    id: '/$investissement',
    path: '/$investissement',
    getParentRoute: () => AppInvestissementsRoute,
  } as any)
const AppGammesSplatRoute = AppGammesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppGammesRoute,
} as any)
const AppEquipementsSplatRoute = AppEquipementsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppEquipementsRoute,
} as any)
const AppDemandesDemandeRoute = AppDemandesDemandeRouteImport.update({
  id: '/$demande',
  path: '/$demande',
  getParentRoute: () => AppDemandesRoute,
} as any)
const AppBibliothequeSplatRoute = AppBibliothequeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppBibliothequeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/login': typeof LoginRoute
  '/bibliotheque': typeof AppBibliothequeRouteWithChildren
  '/demandes': typeof AppDemandesRouteWithChildren
  '/documents': typeof AppDocumentsRoute
  '/equipements': typeof AppEquipementsRouteWithChildren
  '/gammes': typeof AppGammesRouteWithChildren
  '/investissements': typeof AppInvestissementsRouteWithChildren
  '/localisations': typeof AppLocalisationsRouteWithChildren
  '/ordres-travail': typeof AppOrdresTravailRoute
  '/planning': typeof AppPlanningRoute
  '/prestataires': typeof AppPrestatairesRouteWithChildren
  '/profil': typeof AppProfilRoute
  '/registre': typeof AppRegistreRoute
  '/releves': typeof AppRelevesRoute
  '/sites': typeof AppSitesRoute
  '/travaux': typeof AppTravauxRouteWithChildren
  '/utilisateurs': typeof AppUtilisateursRouteWithChildren
  '/bibliotheque/$': typeof AppBibliothequeSplatRoute
  '/demandes/$demande': typeof AppDemandesDemandeRoute
  '/equipements/$': typeof AppEquipementsSplatRoute
  '/gammes/$': typeof AppGammesSplatRoute
  '/investissements/$investissement': typeof AppInvestissementsInvestissementRoute
  '/localisations/$': typeof AppLocalisationsSplatRoute
  '/prestataires/$prestataire': typeof AppPrestatairesPrestataireRoute
  '/travaux/$travaux': typeof AppTravauxTravauxRoute
  '/utilisateurs/$utilisateur': typeof AppUtilisateursUtilisateurRoute
  '/bibliotheque/': typeof AppBibliothequeIndexRoute
  '/demandes/': typeof AppDemandesIndexRoute
  '/investissements/': typeof AppInvestissementsIndexRoute
  '/prestataires/': typeof AppPrestatairesIndexRoute
  '/travaux/': typeof AppTravauxIndexRoute
  '/utilisateurs/': typeof AppUtilisateursIndexRoute
}
export interface FileRoutesByTo {
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/login': typeof LoginRoute
  '/documents': typeof AppDocumentsRoute
  '/equipements': typeof AppEquipementsRouteWithChildren
  '/gammes': typeof AppGammesRouteWithChildren
  '/localisations': typeof AppLocalisationsRouteWithChildren
  '/ordres-travail': typeof AppOrdresTravailRoute
  '/planning': typeof AppPlanningRoute
  '/profil': typeof AppProfilRoute
  '/registre': typeof AppRegistreRoute
  '/releves': typeof AppRelevesRoute
  '/sites': typeof AppSitesRoute
  '/': typeof AppIndexRoute
  '/bibliotheque/$': typeof AppBibliothequeSplatRoute
  '/demandes/$demande': typeof AppDemandesDemandeRoute
  '/equipements/$': typeof AppEquipementsSplatRoute
  '/gammes/$': typeof AppGammesSplatRoute
  '/investissements/$investissement': typeof AppInvestissementsInvestissementRoute
  '/localisations/$': typeof AppLocalisationsSplatRoute
  '/prestataires/$prestataire': typeof AppPrestatairesPrestataireRoute
  '/travaux/$travaux': typeof AppTravauxTravauxRoute
  '/utilisateurs/$utilisateur': typeof AppUtilisateursUtilisateurRoute
  '/bibliotheque': typeof AppBibliothequeIndexRoute
  '/demandes': typeof AppDemandesIndexRoute
  '/investissements': typeof AppInvestissementsIndexRoute
  '/prestataires': typeof AppPrestatairesIndexRoute
  '/travaux': typeof AppTravauxIndexRoute
  '/utilisateurs': typeof AppUtilisateursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/login': typeof LoginRoute
  '/_app/bibliotheque': typeof AppBibliothequeRouteWithChildren
  '/_app/demandes': typeof AppDemandesRouteWithChildren
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/equipements': typeof AppEquipementsRouteWithChildren
  '/_app/gammes': typeof AppGammesRouteWithChildren
  '/_app/investissements': typeof AppInvestissementsRouteWithChildren
  '/_app/localisations': typeof AppLocalisationsRouteWithChildren
  '/_app/ordres-travail': typeof AppOrdresTravailRoute
  '/_app/planning': typeof AppPlanningRoute
  '/_app/prestataires': typeof AppPrestatairesRouteWithChildren
  '/_app/profil': typeof AppProfilRoute
  '/_app/registre': typeof AppRegistreRoute
  '/_app/releves': typeof AppRelevesRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/travaux': typeof AppTravauxRouteWithChildren
  '/_app/utilisateurs': typeof AppUtilisateursRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/bibliotheque/$': typeof AppBibliothequeSplatRoute
  '/_app/demandes/$demande': typeof AppDemandesDemandeRoute
  '/_app/equipements/$': typeof AppEquipementsSplatRoute
  '/_app/gammes/$': typeof AppGammesSplatRoute
  '/_app/investissements/$investissement': typeof AppInvestissementsInvestissementRoute
  '/_app/localisations/$': typeof AppLocalisationsSplatRoute
  '/_app/prestataires/$prestataire': typeof AppPrestatairesPrestataireRoute
  '/_app/travaux/$travaux': typeof AppTravauxTravauxRoute
  '/_app/utilisateurs/$utilisateur': typeof AppUtilisateursUtilisateurRoute
  '/_app/bibliotheque/': typeof AppBibliothequeIndexRoute
  '/_app/demandes/': typeof AppDemandesIndexRoute
  '/_app/investissements/': typeof AppInvestissementsIndexRoute
  '/_app/prestataires/': typeof AppPrestatairesIndexRoute
  '/_app/travaux/': typeof AppTravauxIndexRoute
  '/_app/utilisateurs/': typeof AppUtilisateursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-mot-de-passe'
    | '/login'
    | '/bibliotheque'
    | '/demandes'
    | '/documents'
    | '/equipements'
    | '/gammes'
    | '/investissements'
    | '/localisations'
    | '/ordres-travail'
    | '/planning'
    | '/prestataires'
    | '/profil'
    | '/registre'
    | '/releves'
    | '/sites'
    | '/travaux'
    | '/utilisateurs'
    | '/bibliotheque/$'
    | '/demandes/$demande'
    | '/equipements/$'
    | '/gammes/$'
    | '/investissements/$investissement'
    | '/localisations/$'
    | '/prestataires/$prestataire'
    | '/travaux/$travaux'
    | '/utilisateurs/$utilisateur'
    | '/bibliotheque/'
    | '/demandes/'
    | '/investissements/'
    | '/prestataires/'
    | '/travaux/'
    | '/utilisateurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/definir-mot-de-passe'
    | '/login'
    | '/documents'
    | '/equipements'
    | '/gammes'
    | '/localisations'
    | '/ordres-travail'
    | '/planning'
    | '/profil'
    | '/registre'
    | '/releves'
    | '/sites'
    | '/'
    | '/bibliotheque/$'
    | '/demandes/$demande'
    | '/equipements/$'
    | '/gammes/$'
    | '/investissements/$investissement'
    | '/localisations/$'
    | '/prestataires/$prestataire'
    | '/travaux/$travaux'
    | '/utilisateurs/$utilisateur'
    | '/bibliotheque'
    | '/demandes'
    | '/investissements'
    | '/prestataires'
    | '/travaux'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/_app'
    | '/definir-mot-de-passe'
    | '/login'
    | '/_app/bibliotheque'
    | '/_app/demandes'
    | '/_app/documents'
    | '/_app/equipements'
    | '/_app/gammes'
    | '/_app/investissements'
    | '/_app/localisations'
    | '/_app/ordres-travail'
    | '/_app/planning'
    | '/_app/prestataires'
    | '/_app/profil'
    | '/_app/registre'
    | '/_app/releves'
    | '/_app/sites'
    | '/_app/travaux'
    | '/_app/utilisateurs'
    | '/_app/'
    | '/_app/bibliotheque/$'
    | '/_app/demandes/$demande'
    | '/_app/equipements/$'
    | '/_app/gammes/$'
    | '/_app/investissements/$investissement'
    | '/_app/localisations/$'
    | '/_app/prestataires/$prestataire'
    | '/_app/travaux/$travaux'
    | '/_app/utilisateurs/$utilisateur'
    | '/_app/bibliotheque/'
    | '/_app/demandes/'
    | '/_app/investissements/'
    | '/_app/prestataires/'
    | '/_app/travaux/'
    | '/_app/utilisateurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DefinirMotDePasseRoute: typeof DefinirMotDePasseRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-mot-de-passe': {
      id: '/definir-mot-de-passe'
      path: '/definir-mot-de-passe'
      fullPath: '/definir-mot-de-passe'
      preLoaderRoute: typeof DefinirMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/travaux': {
      id: '/_app/travaux'
      path: '/travaux'
      fullPath: '/travaux'
      preLoaderRoute: typeof AppTravauxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releves': {
      id: '/_app/releves'
      path: '/releves'
      fullPath: '/releves'
      preLoaderRoute: typeof AppRelevesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registre': {
      id: '/_app/registre'
      path: '/registre'
      fullPath: '/registre'
      preLoaderRoute: typeof AppRegistreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prestataires': {
      id: '/_app/prestataires'
      path: '/prestataires'
      fullPath: '/prestataires'
      preLoaderRoute: typeof AppPrestatairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning': {
      id: '/_app/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordres-travail': {
      id: '/_app/ordres-travail'
      path: '/ordres-travail'
      fullPath: '/ordres-travail'
      preLoaderRoute: typeof AppOrdresTravailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/localisations': {
      id: '/_app/localisations'
      path: '/localisations'
      fullPath: '/localisations'
      preLoaderRoute: typeof AppLocalisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investissements': {
      id: '/_app/investissements'
      path: '/investissements'
      fullPath: '/investissements'
      preLoaderRoute: typeof AppInvestissementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gammes': {
      id: '/_app/gammes'
      path: '/gammes'
      fullPath: '/gammes'
      preLoaderRoute: typeof AppGammesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipements': {
      id: '/_app/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof AppEquipementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandes': {
      id: '/_app/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AppDemandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bibliotheque': {
      id: '/_app/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AppBibliothequeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilisateurs/': {
      id: '/_app/utilisateurs/'
      path: '/'
      fullPath: '/utilisateurs/'
      preLoaderRoute: typeof AppUtilisateursIndexRouteImport
      parentRoute: typeof AppUtilisateursRoute
    }
    '/_app/travaux/': {
      id: '/_app/travaux/'
      path: '/'
      fullPath: '/travaux/'
      preLoaderRoute: typeof AppTravauxIndexRouteImport
      parentRoute: typeof AppTravauxRoute
    }
    '/_app/prestataires/': {
      id: '/_app/prestataires/'
      path: '/'
      fullPath: '/prestataires/'
      preLoaderRoute: typeof AppPrestatairesIndexRouteImport
      parentRoute: typeof AppPrestatairesRoute
    }
    '/_app/investissements/': {
      id: '/_app/investissements/'
      path: '/'
      fullPath: '/investissements/'
      preLoaderRoute: typeof AppInvestissementsIndexRouteImport
      parentRoute: typeof AppInvestissementsRoute
    }
    '/_app/demandes/': {
      id: '/_app/demandes/'
      path: '/'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AppDemandesIndexRouteImport
      parentRoute: typeof AppDemandesRoute
    }
    '/_app/bibliotheque/': {
      id: '/_app/bibliotheque/'
      path: '/'
      fullPath: '/bibliotheque/'
      preLoaderRoute: typeof AppBibliothequeIndexRouteImport
      parentRoute: typeof AppBibliothequeRoute
    }
    '/_app/utilisateurs/$utilisateur': {
      id: '/_app/utilisateurs/$utilisateur'
      path: '/$utilisateur'
      fullPath: '/utilisateurs/$utilisateur'
      preLoaderRoute: typeof AppUtilisateursUtilisateurRouteImport
      parentRoute: typeof AppUtilisateursRoute
    }
    '/_app/travaux/$travaux': {
      id: '/_app/travaux/$travaux'
      path: '/$travaux'
      fullPath: '/travaux/$travaux'
      preLoaderRoute: typeof AppTravauxTravauxRouteImport
      parentRoute: typeof AppTravauxRoute
    }
    '/_app/prestataires/$prestataire': {
      id: '/_app/prestataires/$prestataire'
      path: '/$prestataire'
      fullPath: '/prestataires/$prestataire'
      preLoaderRoute: typeof AppPrestatairesPrestataireRouteImport
      parentRoute: typeof AppPrestatairesRoute
    }
    '/_app/localisations/$': {
      id: '/_app/localisations/$'
      path: '/$'
      fullPath: '/localisations/$'
      preLoaderRoute: typeof AppLocalisationsSplatRouteImport
      parentRoute: typeof AppLocalisationsRoute
    }
    '/_app/investissements/$investissement': {
      id: '/_app/investissements/$investissement'
      path: '/$investissement'
      fullPath: '/investissements/$investissement'
      preLoaderRoute: typeof AppInvestissementsInvestissementRouteImport
      parentRoute: typeof AppInvestissementsRoute
    }
    '/_app/gammes/$': {
      id: '/_app/gammes/$'
      path: '/$'
      fullPath: '/gammes/$'
      preLoaderRoute: typeof AppGammesSplatRouteImport
      parentRoute: typeof AppGammesRoute
    }
    '/_app/equipements/$': {
      id: '/_app/equipements/$'
      path: '/$'
      fullPath: '/equipements/$'
      preLoaderRoute: typeof AppEquipementsSplatRouteImport
      parentRoute: typeof AppEquipementsRoute
    }
    '/_app/demandes/$demande': {
      id: '/_app/demandes/$demande'
      path: '/$demande'
      fullPath: '/demandes/$demande'
      preLoaderRoute: typeof AppDemandesDemandeRouteImport
      parentRoute: typeof AppDemandesRoute
    }
    '/_app/bibliotheque/$': {
      id: '/_app/bibliotheque/$'
      path: '/$'
      fullPath: '/bibliotheque/$'
      preLoaderRoute: typeof AppBibliothequeSplatRouteImport
      parentRoute: typeof AppBibliothequeRoute
    }
  }
}

interface AppBibliothequeRouteChildren {
  AppBibliothequeSplatRoute: typeof AppBibliothequeSplatRoute
  AppBibliothequeIndexRoute: typeof AppBibliothequeIndexRoute
}

const AppBibliothequeRouteChildren: AppBibliothequeRouteChildren = {
  AppBibliothequeSplatRoute: AppBibliothequeSplatRoute,
  AppBibliothequeIndexRoute: AppBibliothequeIndexRoute,
}

const AppBibliothequeRouteWithChildren = AppBibliothequeRoute._addFileChildren(
  AppBibliothequeRouteChildren,
)

interface AppDemandesRouteChildren {
  AppDemandesDemandeRoute: typeof AppDemandesDemandeRoute
  AppDemandesIndexRoute: typeof AppDemandesIndexRoute
}

const AppDemandesRouteChildren: AppDemandesRouteChildren = {
  AppDemandesDemandeRoute: AppDemandesDemandeRoute,
  AppDemandesIndexRoute: AppDemandesIndexRoute,
}

const AppDemandesRouteWithChildren = AppDemandesRoute._addFileChildren(
  AppDemandesRouteChildren,
)

interface AppEquipementsRouteChildren {
  AppEquipementsSplatRoute: typeof AppEquipementsSplatRoute
}

const AppEquipementsRouteChildren: AppEquipementsRouteChildren = {
  AppEquipementsSplatRoute: AppEquipementsSplatRoute,
}

const AppEquipementsRouteWithChildren = AppEquipementsRoute._addFileChildren(
  AppEquipementsRouteChildren,
)

interface AppGammesRouteChildren {
  AppGammesSplatRoute: typeof AppGammesSplatRoute
}

const AppGammesRouteChildren: AppGammesRouteChildren = {
  AppGammesSplatRoute: AppGammesSplatRoute,
}

const AppGammesRouteWithChildren = AppGammesRoute._addFileChildren(
  AppGammesRouteChildren,
)

interface AppInvestissementsRouteChildren {
  AppInvestissementsInvestissementRoute: typeof AppInvestissementsInvestissementRoute
  AppInvestissementsIndexRoute: typeof AppInvestissementsIndexRoute
}

const AppInvestissementsRouteChildren: AppInvestissementsRouteChildren = {
  AppInvestissementsInvestissementRoute: AppInvestissementsInvestissementRoute,
  AppInvestissementsIndexRoute: AppInvestissementsIndexRoute,
}

const AppInvestissementsRouteWithChildren =
  AppInvestissementsRoute._addFileChildren(AppInvestissementsRouteChildren)

interface AppLocalisationsRouteChildren {
  AppLocalisationsSplatRoute: typeof AppLocalisationsSplatRoute
}

const AppLocalisationsRouteChildren: AppLocalisationsRouteChildren = {
  AppLocalisationsSplatRoute: AppLocalisationsSplatRoute,
}

const AppLocalisationsRouteWithChildren =
  AppLocalisationsRoute._addFileChildren(AppLocalisationsRouteChildren)

interface AppPrestatairesRouteChildren {
  AppPrestatairesPrestataireRoute: typeof AppPrestatairesPrestataireRoute
  AppPrestatairesIndexRoute: typeof AppPrestatairesIndexRoute
}

const AppPrestatairesRouteChildren: AppPrestatairesRouteChildren = {
  AppPrestatairesPrestataireRoute: AppPrestatairesPrestataireRoute,
  AppPrestatairesIndexRoute: AppPrestatairesIndexRoute,
}

const AppPrestatairesRouteWithChildren = AppPrestatairesRoute._addFileChildren(
  AppPrestatairesRouteChildren,
)

interface AppTravauxRouteChildren {
  AppTravauxTravauxRoute: typeof AppTravauxTravauxRoute
  AppTravauxIndexRoute: typeof AppTravauxIndexRoute
}

const AppTravauxRouteChildren: AppTravauxRouteChildren = {
  AppTravauxTravauxRoute: AppTravauxTravauxRoute,
  AppTravauxIndexRoute: AppTravauxIndexRoute,
}

const AppTravauxRouteWithChildren = AppTravauxRoute._addFileChildren(
  AppTravauxRouteChildren,
)

interface AppUtilisateursRouteChildren {
  AppUtilisateursUtilisateurRoute: typeof AppUtilisateursUtilisateurRoute
  AppUtilisateursIndexRoute: typeof AppUtilisateursIndexRoute
}

const AppUtilisateursRouteChildren: AppUtilisateursRouteChildren = {
  AppUtilisateursUtilisateurRoute: AppUtilisateursUtilisateurRoute,
  AppUtilisateursIndexRoute: AppUtilisateursIndexRoute,
}

const AppUtilisateursRouteWithChildren = AppUtilisateursRoute._addFileChildren(
  AppUtilisateursRouteChildren,
)

interface AppRouteChildren {
  AppBibliothequeRoute: typeof AppBibliothequeRouteWithChildren
  AppDemandesRoute: typeof AppDemandesRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEquipementsRoute: typeof AppEquipementsRouteWithChildren
  AppGammesRoute: typeof AppGammesRouteWithChildren
  AppInvestissementsRoute: typeof AppInvestissementsRouteWithChildren
  AppLocalisationsRoute: typeof AppLocalisationsRouteWithChildren
  AppOrdresTravailRoute: typeof AppOrdresTravailRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppPrestatairesRoute: typeof AppPrestatairesRouteWithChildren
  AppProfilRoute: typeof AppProfilRoute
  AppRegistreRoute: typeof AppRegistreRoute
  AppRelevesRoute: typeof AppRelevesRoute
  AppSitesRoute: typeof AppSitesRoute
  AppTravauxRoute: typeof AppTravauxRouteWithChildren
  AppUtilisateursRoute: typeof AppUtilisateursRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliothequeRoute: AppBibliothequeRouteWithChildren,
  AppDemandesRoute: AppDemandesRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEquipementsRoute: AppEquipementsRouteWithChildren,
  AppGammesRoute: AppGammesRouteWithChildren,
  AppInvestissementsRoute: AppInvestissementsRouteWithChildren,
  AppLocalisationsRoute: AppLocalisationsRouteWithChildren,
  AppOrdresTravailRoute: AppOrdresTravailRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppPrestatairesRoute: AppPrestatairesRouteWithChildren,
  AppProfilRoute: AppProfilRoute,
  AppRegistreRoute: AppRegistreRoute,
  AppRelevesRoute: AppRelevesRoute,
  AppSitesRoute: AppSitesRoute,
  AppTravauxRoute: AppTravauxRouteWithChildren,
  AppUtilisateursRoute: AppUtilisateursRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DefinirMotDePasseRoute: DefinirMotDePasseRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
